---
- name: Set deamon {{ name }} state {{ state }} enabled {{ enabled }} daemon-reload {{ daemonReload }}
  systemd:
    name: "{{ name }}"
    state: "{{ state }}"
    enabled: "{{ enabled }}"
    daemon-reload: "{{ daemonReload }}"
